
tasks:
  - init: mvn dependency:resolve install -DskipTests=false

gitConfig:
  alias.st: status
  alias.ci: commit
  alias.lg: log --graph

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - ms-vscode.live-server
