
tasks:
  - init: mvn dependency:resolve install -DskipTests=false
  - command: "echo '⏱ If this is a fresh workspace, please wait 5-10s before opening a .java file: the language server needs to warm up!'"

gitConfig:
  alias.st: status
  alias.ci: commit
  alias.lg: log --graph

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-maven
    - ms-vscode.live-server
    - epsilon.language-epsilon
